[programs.devnet]
solana_project = "9qKWyzr36SvhEw6RjDQL1c9NWCdaMwXy2gDULPEyJY7D"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/adametrnal/.config/solana/id.json"

[scripts]
test = "node tests/solana-project.js"
