[programs.localnet]
solana_project = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/adametrnal/.config/solana/id.json"

[scripts]
test = "node tests/solana-project.js"
